version: '3'
networks:
  backend:
    driver: bridge
volumes:
  mysql:
    driver: local
services:
  mysql_economics:
    image: mysql:5.7.25
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
      - ./docker/mysql/start_scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  app:
    build: .
    volumes:
      - ./python:/usr/src/app/python
      - ./data:/usr/src/app/data
    tty: true
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mysql_economics
      - DELETE_CODE=${DELETE_CODE}
    depends_on:
      - mysql_economics
    networks:
      - backend
    ports:
      - 80:5000
