version: '3.7'
networks:
  proxy:
    external: true
volumes:
  mysql:
    driver: local
services:
  mysql_economics:
    image: mysql:5.7.25
    restart: always
    networks:
      proxy:
        aliases:
          - ${MYSQL_HOST}
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    configs:
      - source: mysql_config
        target: /etc/mysql/conf.d/low-mem.cnf
        mode: 644
        gid: "1000"
        uid: "1000"
      - source: mysql_schema
        target: /docker-entrypoint-initdb.d/schema.sql
        mode: 644
        gid: "1000"
        uid: "1000"
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      mode: replicated
      placement:
        constraints:
          - node.role == manager
          - node.labels.server == 2
  app:
    build: .
    image: economics:latest
    volumes:
      - ./python:/usr/src/app/python
      - ./data:/usr/src/app/data
    tty: true
    env_file:
      - .env
    depends_on:
      - mysql_economics
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"
        traefik.port: "5000"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "Host:economics.maxifom.com"
        traefik.frontend.whiteList.useXForwardedFor: "true"
      replicas: 1
      restart_policy:
        condition: any
      mode: replicated
      placement:
        constraints:
          - node.role == manager
          - node.labels.server == 2
configs:
  mysql_config:
    file: ./docker/mysql/conf.d/low-mem.cnf
  mysql_schema:
    file: ./docker/mysql/start_scripts/mysql-schema.sql