version: '3'
volumes:
  mysql:
    driver: local
services:
  mysql:
    image: mysql:5.7.25
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=economics
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql